# keyboard
repeat_rate=60
repeat_delay=320
numlockon=1
xkb_rules_layout=us

# Key Bindings
# key name refer to `xev` or `wev` command output,
# mod keys name: super,ctrl,alt,shift,none

# reload config
bind=SUPER,r,reload_config

# menu and terminal
bind=Alt,space,spawn,rofi -config ~/.config/mango/rofi/config.rasi -show drun
bind=super,c,spawn,rofi -show calc -modi calc -no-show-match -no-sort
#bind=Alt,Return,spawn,foot
bind=Ctrl+Alt,t,spawn,kitty

# exit
bind=SUPER+shift,q,quit
bind=super,q,killclient,

# switch window focus
bind=super,j,focusstack,next
bind=super,k,focusstack,last

# Move window focus
bind=super+shift,j,exchange_stack_client,next
bind=super+shift,k,exchange_stack_client,last

# swap window
#bind=SUPER+SHIFT,Up,exchange_client,up
#bind=SUPER+SHIFT,Down,exchange_client,down
#bind=SUPER+SHIFT,Left,exchange_client,left
#bind=SUPER+SHIFT,Right,exchange_client,right

# switch window status
bind=SUPER,g,toggleglobal,
bind=ALT,Tab,toggleoverview,
bind=super,space,togglefloating,
#bind=ALT,a,togglemaximizescreen,
bind=super,f,togglefullscreen,
bind=ALT+SHIFT,f,spawn,firefox,
#bind=SUPER,i,minimized,
bind=SUPER,o,toggleoverlay,
bind=SUPER+SHIFT,I,restore_minimized
#bind=ALT,z,toggle_scratchpad

# scroller layout
#bind=ALT,e,set_proportion,1.0
#bind=ALT,x,switch_proportion_preset,
#bind=alt+super+ctrl,Left,scroller_stack,left
#bind=alt+super+ctrl,Right,scroller_stack,right
#bind=alt+super+ctrl,Up,scroller_stack,up
#bind=alt+super+ctrl,Down,scroller_stack,down

#dwindle layout(manual split mode)
bind=alt+shift,Return,dwindle_toggle_split_direction

# switch layout
bind=SUPER,n,switch_layout

# tag switch
#bind=SUPER,Left,viewtoleft,0
#bind=CTRL,Left,viewtoleft_have_client,0
#bind=SUPER,Right,viewtoright,0
#bind=CTRL,Right,viewtoright_have_client,0
#bind=CTRL+SUPER,Left,tagtoleft,0
#bind=CTRL+SUPER,Right,tagtoright,0

bind=super,1,view,1,0
bind=super,2,view,2,0
bind=super,3,view,3,0
bind=super,4,view,4,0
bind=super,5,view,5,0
bind=super,6,view,6,0
bind=super,7,view,7,0
bind=super,8,view,8,0
bind=super,9,view,9,0

# tag: move client to the tag and focus it
# tagsilent: move client to the tag and not focus it
# bind=Alt,1,tagsilent,1
bind=super+shift,1,tagsilent,1,0
bind=super+shift,2,tagsilent,2,0
bind=super+shift,3,tagsilent,3,0
bind=super+shift,4,tagsilent,4,0
bind=super+shift,5,tagsilent,5,0
bind=super+shift,6,tagsilent,6,0
bind=super+shift,7,tagsilent,7,0
bind=super+shift,8,tagsilent,8,0
bind=super+shift,9,tagsilent,9,0

# monitor switch
bind=super+shift,comma,tagmon,left
bind=super+shift,period,tagmon,right
bind=SUPER,comma,focusmon,left
bind=SUPER,period,focusmon,right

# gaps
bind=super+SHIFT,X,incgaps,1
bind=super+SHIFT,Z,incgaps,-1
bind=super+SHIFT,R,togglegaps

# movewin
#bind=CTRL+SHIFT,Up,movewin,+0,-50
#bind=CTRL+SHIFT,Down,movewin,+0,+50
#bind=CTRL+SHIFT,Left,movewin,-50,+0
#bind=CTRL+SHIFT,Right,movewin,+50,+0

# resizewin
#bind=CTRL+ALT,Up,resizewin,+0,-50
#bind=CTRL+ALT,Down,resizewin,+0,+50
bind=super,h,resizewin,-50,+0
bind=super,l,resizewin,+50,+0

# Mouse Button Bindings
# btn_left and btn_right can't bind none mod key
mousebind=alt,btn_left,moveresize,curmove
#mousebind=NONE,btn_middle,togglemaximizescreen,0
mousebind=alt,btn_right,moveresize,curresize

# Axis Bindings
#axisbind=SUPER,UP,viewtoleft_have_client
#axisbind=SUPER,DOWN,viewtoright_have_client

# brightness and volume
bind=none,XF86AudioRaiseVolume,spawn,~/.config/mango/scripts/volume.sh up
bind=none,XF86AudioLowerVolume,spawn,~/.config/mango/scripts/volume.sh down
bind=none,XF86MonBrightnessUp,spawn,~/.config/mango/scripts/brightness.sh up
bind=none,XF86MonBrightnessDown,spawn,~/.config/mango/scripts/brightness.sh down

# Media keys: 
bind=NONE,XF86AudioNext,spawn,playerctl next
bind=NONE,XF86AudioPrev,spawn,playerctl previous
bind=NONE,XF86AudioPlay,spawn,playerctl play-pause


bind=super+shift,s,spawn_shell,grim -g "$(slurp -b '#2E2A1E55' -c '#fb751bff')" -t png - | wl-copy

bind=super,e,spawn,dolphin
bind=super,v,spawn,cursor-clip

